
import {
    javadezzati , adelferdosipourfan , ahmadmehranfar , amir_aghaee , amirmohammadzand , 
    behrangalavi , dirbaz_kambiz , ehsankhajeamiri , hamedkomaily , ehsanalikhani , hamidgoodarzi , 
    javad_razavian , leomessi , mehrammodiri , mohammadmotamedi , rezaattaran , rezagolzar , roozbehbemani , 
    sirmajid_salehi , yousefteymoori
    } from './profileImages';

export const instagramApi = [
    {id:1 ,
    userName:"hamidgoodarzi",     
    name:"Hamid Goodarzi" ,
    image:hamidgoodarzi ,
    bio:"iranian actor" , 
    followers:{num:"1/1" , unit:"میلیون"} ,
    following:"63" ,
    posts:"77" ,
    },
    {id:2, 
    userName:"hamedkomaily",    
    name:"Hamed Komaily",
    image:hamedkomaily ,
    bio: "" , 
    followers: {num:"621" , unit:"هزار"} ,
    following:"398" ,
    posts:"383" ,
    },
    {id: 3, 
    userName:"amirmohammadzand",    
    name: "Amir Mohammad Zand" ,
    image:amirmohammadzand ,
    bio:"actor/director" , 
    followers:{num:"674" , unit:"هزار"} ,
    following:"99" ,
    posts:"86" ,
    },
    {id: 4,
    userName:"sirmajid_salehi",     
    name:"Majid Salehi" ,
    image:sirmajid_salehi ,
    bio: "Iranian actor, director , writter and film producer" , 
    followers: {num:"1/3" , unit:"میلیون"} ,
    following:"853" ,
    posts:"103" ,
    },
    {id: 5, 
    userName:"mohammadmotamedi",    
    name:"Mohammad Motamedi" ,
    image:mohammadmotamedi ,
    bio: "Persian tranditional singer" , 
    followers:{num:"527" , unit:"هزار"} ,
    following:"237" ,
    posts:"474" ,
    },
    {id: 6,
    userName:"mehrammodiri",     
    name:"Mehran Modiri" ,
    image:mehrammodiri ,
    bio: "تنها صفحه رسمی مهران مدیری" , 
    followers: {num:"2/3" , unit:"میلیون"} ,
    following:"87" ,
    posts:"139" ,
    },
    {id: 7, 
    userName:"amir_aghaee",    
    name: "Amir Aghaee" ,
    image:amir_aghaee ,
    bio: "iranian actor", 
    followers:{num:"1/2" , unit:"میلیون"} ,
    following:"2" ,
    posts:"347" ,
    },
    {id: 8, 
    userName:"behrangalavi_official",    
    name:"Behrang alavi",
    image:behrangalavi ,
    bio:"بازیگر" , 
    followers: {num:"2" , unit:"میلیون"} ,
    following: "617" ,
    posts: "446" ,
    },
    {id: 9, 
    userName:"javadezzati",    
    name: "Javad Ezzati",
    image:javadezzati ,
    bio:"" , 
    followers:{num:"4/7" , unit:"میلیون"} ,
    following:"491" ,
    posts:"354" ,
    },
    {id: 10,
    userName:"rezagolzar",     
    name:"Mohammad Reza Golzar" ,
    image:rezagolzar ,
    bio:"The official page of mohammad reza golzar" , 
    followers: {num:"12/2" , unit:"میلیون"},
    following:"92" ,
    posts: "1783",
    },
    {id: 11,
    userName:"roozbehbemani",     
    name:"roozbeh bemani|روزبه بمانی" ,
    image:roozbehbemani ,
    bio:"مدیر برنامه ها : شاهد صادقپور" , 
    followers:{num:"626" , unit:"هزار"} ,
    following:"59" ,
    posts:"246" ,
    },
    {id: 12,
    userName:"yousefteymoori",     
    name: "Yousef Teymoori | یوسف تیموری" ,
    image:yousefteymoori ,
    bio:"Actor" , 
    followers:{num:"1" , unit:"میلیون"} ,
    following:"176" ,
    posts:"41" ,
    },
    {id:13,
    userName:"dirbaz_kambiz",     
    name: "کامبیز دیرباز",
    image:dirbaz_kambiz ,
    bio: "هر چی دوست دارید زیر پست هام تبلیغ کنید. من که راضیم" , 
    followers:{num:"4" , unit:"میلیون"} ,
    following: "0",
    posts:"230" ,
    },
    {id:14,
    userName:"adelferdosipourfan",     
    name:"عادل فردوسی پور" ,
    image: adelferdosipourfan,
    bio: "بزرگترین و تنها پیج رسمی هواداران عادل فردوسی پور", 
    followers:{num:"2/4" , unit:"میلیون"} ,
    following: "500",
    posts: "2732",
    },
    {id:15,
    userName:"rezaattaran",     
    name: "Reza Attaran" ,
    image:rezaattaran ,
    bio: "We only live once" , 
    followers: {num:"6/8" , unit:"میلیون"} ,
    following:"40" ,
    posts:"318" ,
    },
    {id:16,
    userName:"leomessi",     
    name:"Leo Messi" ,
    image:leomessi ,
    bio: "Welcome to the official Leo Messi instagram account", 
    followers:{num:"345" , unit:"میلیون"} ,
    following:"297" ,
    posts:"875" ,
    },
    {id:17,
    userName:"ahmadmehranfar",     
    name: "Ahmad Mehranfar" ,
    image:ahmadmehranfar ,
    bio: "Iranian Actor" , 
    followers:{num:"3/5" , unit:"میلیون"} ,
    following:"267" ,
    posts:"324" ,
    },
    {id:18,
    userName:"ehsanalikhani",     
    name:"احسان علیخانی" ,
    image: ehsanalikhani ,
    bio: "TV host , Producer" , 
    followers: {num:"3/8" , unit:"میلیون"} ,
    following:"5" ,
    posts: "432",
    },
    {id:19,
    userName:"ehsankhajeamiri",     
    name: "Ehsan Khaje Amiri",
    image: ehsankhajeamiri ,
    bio: "" , 
    followers:{num:"1/2" , unit:"میلیون"} ,
    following:"458" ,
    posts:"78" ,
    },
    {id:20,
    userName:"javad_razavian",
    name: "Javad Razavian" ,
    image: javad_razavian ,
    bio: "Iranian Actor" , 
    followers: {num:"1/6" , unit:"میلیون"} ,
    following: "785" ,
    posts: "118" ,
    }
]