
import{
    one , two , three , four , five , six , seven , eight , nine , ten
} from './posts'
import {
    javadezzati , amir_aghaee , amirmohammadzand , 
    behrangalavi , hamedkomaily ,hamidgoodarzi , mehrammodiri , mohammadmotamedi ,rezagolzar , 
    sirmajid_salehi
    } from './profileImages';
    
export const posts = [
    {id:1 ,
    profileImage:hamidgoodarzi ,    
    image:one ,
    userName:"hamidgoodarzi" ,
    likes:"8007" ,
    comments:"297" ,
    describtion:"تابستان" ,
    time:"18 june" ,
    like:false,
    save:false
    },
    {id:2 ,
    profileImage:hamedkomaily ,    
    image:two ,
    userName:"hamedkomaily" ,
    likes: "17559" ,
    comments:"125" ,
    describtion:"1401.4.14" ,
    time:"3 days ago" ,
    like:false,
    save:false
    },
    {id:3 ,
    profileImage:amirmohammadzand ,    
    image:three ,
    userName:"amirmohammadzand" ,
    likes: "1997" ,
    comments:"254" ,
    describtion:"تنها شهامت عبور از راه است که راه را پدیدار می‌سازد" ,
    time:"6 june" ,
    like:false,
    save:false
    },
    {id:4 ,
    profileImage:sirmajid_salehi ,    
    image:four ,
    userName:"sirmajid_salehi" ,
    likes:"4597" ,
    comments:"457" ,
    describtion:"#majid-salehi" ,
    time:"3 hours ago" ,
    like:false,
    save:false
    },
    {id:5 ,
    profileImage:mohammadmotamedi ,    
    image:five ,
    userName:"mohammadmotamedi" ,
    likes:"7884" ,
    comments:"236" ,
    describtion:"#mohammad-motamedi" ,
    time:"1 day ago" ,
    like:false,
    save:false
    },
    {id:6 ,
    profileImage:mehrammodiri ,    
    image:six ,
    userName:"mehranmodiri" ,
    likes:"45963" ,
    comments:"1246" ,
    describtion:"" ,
    time:"2 days ago" ,
    like:false,
    save:false
    },
    {id:7 ,
    profileImage:amir_aghaee ,    
    image:seven ,
    userName:"amir_aghaee" ,
    likes:"78546" ,
    comments:"2391" ,
    describtion:"" ,
    time:"3 days ago" ,
    like:false,
    save:false
    },
    {id:8 ,
    profileImage:behrangalavi ,    
    image:eight  ,
    userName:"behrangalavi_official" ,
    likes:"5478" ,
    comments:"703" ,
    describtion:"#بهرنگ" ,
    time:"5 hours ago" ,
    like:false,
    save:false
    },
    {id:9 ,
    profileImage:javadezzati ,    
    image:nine ,
    userName:"javadezzati" ,
    likes:"22365" ,
    comments:"1036" ,
    describtion:"#javad-ezzati" ,
    time:"12 hours ago" ,
    like:false,
    save:false
    },
    {id:10 ,
    profileImage:rezagolzar ,    
    image:ten ,
    userName:"rezagolzar" ,
    likes:"22365" ,
    comments:"4581" ,
    describtion:"#reza-golzar" ,
    time:"30 minutes ago" ,
    like:false,
    save:false
    }
]